name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/.
        ##
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install dependency
        run: npm install --force
      - name: Build dependency
        run: npm run build
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: sudo rm -rf .git

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr
          remote_path: ~/frontend/
          remote_host: 13.213.11.180
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_KEY }}
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: "unnecessary"
      - name: Start application
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.213.11.180 << 'EOF'
            sudo cp -r /home/ubuntu/frontend /var/www
            pm2 delete frontend || true
            pm2 start npm --name "frontend" -- start
          EOF

# pm2 restart frontend-v1